# Generated by Django 4.2.11 on 2024-04-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_register_registration_rename_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='notes',
            field=models.CharField(default='no notes', max_length=100),
            preserve_default=False,
        ),
    ]
