# Generated by Django 4.2.11 on 2024-04-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_registration_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
