# Generated by Django 4.2.11 on 2024-04-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_membership_registration_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='membership',
        ),
    ]
