# Generated by Django 4.2.11 on 2024-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_delete_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=30)),
            ],
        ),
    ]
