# Generated by Django 4.2.11 on 2025-01-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_membership_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=60, null=True)),
                ('icluded', models.BooleanField(default=True)),
            ],
        ),
    ]
