# Generated by Django 4.2.11 on 2025-01-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_inclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inclusion',
            old_name='icluded',
            new_name='included',
        ),
    ]
