# Generated by Django 4.2.11 on 2025-01-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_rename_icluded_inclusion_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='includes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
