# Generated by Django 4.2.11 on 2025-01-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_roomtype_amount_roomtype_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='regdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
